#include "parser/parser.h"

#include "logging.h"
#include "main.h"

parser::UniqueFile parser::readFile(char* fileName) {
  FILE* file = fopen(fileName, "r");

  if (!file) {
    if (isDebug)
      perror("fopen");
    throw std::ios_base::failure("Failed to open file: '" + std::string(fileName) + "'.");
  }

  return UniqueFile(file);
}

ASTNode* parser::parseCode(FILE* source) {
  // Set the input for the lexer to the provided source file.
  yyin = source;

  // Call the parsing function generated by Bison.
  int parsingResult = yyparse();

  // Check the result of parsing for errors.
  if (parsingResult == 1) {
    logsys::get()->error("Parsing error: syntax error in the input code.");
    throw parser::SyntaxError("Parsing error: syntax error in the input code.");
  } else if (parsingResult == 2) {
    logsys::get()->error("Parsing error: memory exhaustion during parsing.");
    throw parser::MemoryExhaustion("Parsing error: memory exhaustion during parsing.");
  }

  // Return the root node of the AST, which should have been set by the parser.
  return root;
}